{% set name = "Oasis" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url : https://github.com/MAfarrag/Oasis/archive/{{ version }}.tar.gz
  sha256:  b25f5a2190179755540a26009ce8cbc4271eda8d0b28d278d1cf81b6ca4d87a1

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv'

requirements:
  host:
    - python >=2.7
    - pip
    - numpy
  run:
    - python >=2.7
    - pip
    - numpy

test:
  imports:
    - Oasis

about:
  home: https://github.com/MAfarrag/HAPI/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Harmony Search Optimization Algorithm'
  description: |
    Harmony Search Optimization Algorithm.
  dev_url: https://github.com/MAfarrag/Oasis
  doc_url: https://oasis-optimization.readthedocs.io/

extra:
  recipe-maintainers:
    - MAfarrag
